export default {
  appName: require("../icon/appName.png"),
  appLogo: require("../icon/appLogo.png"),
  forwardIcon: require("../icon/forwardIcon.png"),
  backwardIcon: require("../icon/backwardIcon.png"),
  splashTopBackground: require("../icon/splashTopBackground.png"),
  splashBottomBackground: require("../icon/splashBottomBackground.png"),
  bottomBackgroung: require("../icon/bottomBackgroundImage.png"),
  topBackgroung: require("../icon/topBackgroundImage.png"),
  editIcon: require("../icon/editIcon.png"),
  eventIcon: require("../icon/eventIcon.png"),
  homeIcon: require("../icon/homeIcon.png"),
  mailIcon: require("../icon/mailIcon.png"),
  phoneIcon: require("../icon/phoneIcon.png"),
  whatsAppIcon: require("../icon/whatsAppIcon.png"),
  smallPhoneIcon: require("../icon/smallPhoneIcon.png"),
  smallMailIcon: require("../icon/smallMailIcon.png"),
  darkPhoneIcon: require("../icon/darkPhoneIcon.png"),
  darkWhatsappIcon: require("../icon/darkWhatsappIcon.png"),
  cameraIcon: require("../icon/camera.png"),
  galleryIcon: require("../icon/gallery.png"),
  projectImg1: require("../icon/projectImg1.png"),
  projectImg2: require("../icon/projectImg2.png"),
};
